"""Asynchronous database layer built on SQLAlchemy 2.0 Core.

Backend-agnostic by design: point ``DATABASE_URL`` at PostgreSQL
(``postgresql+asyncpg://…``) for production scale, or SQLite
(``sqlite+aiosqlite:///…``) for development — the same SQL runs on both.

Highlights
----------
* Named-parameter SQL (``:user_id``) executed via ``text()``.
* ``async with db.transaction():`` — async context manager with
  automatic COMMIT on success and ROLLBACK on any exception.
* Dialect-aware, versioned schema migrations (custom lightweight runner
  — no Alembic dependency for a schema this size).
* Guild-scoped schema: players are keyed ``(guild_id, user_id)``; the
  sentinel guild ``0`` hosts global-scope rows when the economy runs in
  global mode. Cross-server identity and badges live in separate
  global tables.
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any, AsyncIterator, Callable, Final, Mapping, Sequence

from sqlalchemy import text
from sqlalchemy.sql.elements import TextClause
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, create_async_engine

from bot.core.exceptions import DatabaseError

logger = logging.getLogger("gacha.database")

SCHEMA_VERSION: int = 2


def _ddl(dialect: str) -> str:
    """Full schema v2 DDL, adjusted for the active dialect."""
    auto_id = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    if dialect == "sqlite":
        auto_id = "INTEGER PRIMARY KEY AUTOINCREMENT"
    return f"""
    CREATE TABLE IF NOT EXISTS guilds (
        guild_id   BIGINT PRIMARY KEY,
        name       TEXT NOT NULL DEFAULT '',
        joined_at  TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS global_users (
        user_id     BIGINT PRIMARY KEY,
        first_seen  TEXT NOT NULL,
        last_seen   TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS players (
        guild_id     BIGINT NOT NULL,
        user_id      BIGINT NOT NULL,
        balance      BIGINT NOT NULL DEFAULT 0,
        xp           INTEGER NOT NULL DEFAULT 0,
        level        INTEGER NOT NULL DEFAULT 1,
        total_pulls  INTEGER NOT NULL DEFAULT 0,
        pity_counter INTEGER NOT NULL DEFAULT 0,
        shards       INTEGER NOT NULL DEFAULT 0,
        created_at   TEXT NOT NULL,
        updated_at   TEXT NOT NULL,
        PRIMARY KEY (guild_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS inventory (
        guild_id BIGINT NOT NULL,
        user_id  BIGINT NOT NULL,
        item_key TEXT NOT NULL,
        quantity INTEGER NOT NULL DEFAULT 1,
        PRIMARY KEY (guild_id, user_id, item_key)
    );

    CREATE TABLE IF NOT EXISTS equipment (
        id        {auto_id},
        guild_id  BIGINT NOT NULL,
        user_id   BIGINT NOT NULL,
        item_key  TEXT NOT NULL,
        slot      TEXT NOT NULL,
        rarity    TEXT NOT NULL,
        level     INTEGER NOT NULL DEFAULT 0,
        attack    INTEGER NOT NULL DEFAULT 0,
        defense   INTEGER NOT NULL DEFAULT 0,
        luck      INTEGER NOT NULL DEFAULT 0,
        equipped  INTEGER NOT NULL DEFAULT 0,
        obtained  TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_equipment_owner ON equipment(guild_id, user_id, equipped);

    CREATE TABLE IF NOT EXISTS upgrades (
        guild_id     BIGINT NOT NULL,
        user_id      BIGINT NOT NULL,
        upgrade_key  TEXT NOT NULL,
        level        INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (guild_id, user_id, upgrade_key)
    );

    CREATE TABLE IF NOT EXISTS huntbots (
        guild_id        BIGINT NOT NULL,
        user_id         BIGINT NOT NULL,
        level           INTEGER NOT NULL DEFAULT 1,
        active          INTEGER NOT NULL DEFAULT 0,
        battery         INTEGER NOT NULL DEFAULT 0,
        last_tick       TEXT,
        unclaimed_coins INTEGER NOT NULL DEFAULT 0,
        unclaimed_items TEXT NOT NULL DEFAULT '',
        hunts_done      INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (guild_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS badges (
        user_id    BIGINT NOT NULL,
        badge_key  TEXT NOT NULL,
        guild_id   BIGINT,             -- NULL => globally-awarded badge
        granted_at TEXT NOT NULL,
        granted_by BIGINT,
        PRIMARY KEY (user_id, badge_key, guild_id)
    );

    CREATE TABLE IF NOT EXISTS economy_log (
        id            {auto_id},
        guild_id      BIGINT NOT NULL,
        user_id       BIGINT NOT NULL,
        delta         BIGINT NOT NULL,
        reason        TEXT NOT NULL,
        balance_after BIGINT NOT NULL,
        created_at    TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_economy_log_owner ON economy_log(guild_id, user_id);

    CREATE TABLE IF NOT EXISTS log_channels (
        guild_id   BIGINT NOT NULL,
        category   TEXT NOT NULL,
        channel_id BIGINT NOT NULL,
        PRIMARY KEY (guild_id, category)
    );
    """


async def _migration_v2(conn: AsyncConnection, dialect: str) -> None:
    """Version 2 — guild-scoped schema (fresh start)."""
    for statement in _ddl_statements(_ddl(dialect)):
        await conn.execute(text(statement))


def _ddl_statements(script: str) -> list[str]:
    """Split a DDL script into individual statements (comments stripped)."""
    statements: list[str] = []
    for raw in script.split(";"):
        cleaned = "\n".join(
            line for line in raw.splitlines() if not line.strip().startswith("--")
        ).strip()
        if cleaned:
            statements.append(cleaned)
    return statements


MIGRATIONS: Final[tuple[tuple[int, Callable[[AsyncConnection, str], Any]], ...]] = (
    (2, _migration_v2),
)

Row = Mapping[str, Any]


class Database:
    """Async facade over a SQLAlchemy async engine."""

    __slots__ = ("_url", "_engine", "_ready")

    def __init__(self, url: str) -> None:
        self._url = url
        self._engine: AsyncEngine | None = None
        self._ready = False

    # -- lifecycle -----------------------------------------------------------

    @property
    def dialect(self) -> str:
        assert self._engine is not None, "database not connected"
        return self._engine.dialect.name

    async def connect(self) -> None:
        if self._ready:
            return
        if self._url.startswith("sqlite"):
            # ensure the parent directory of the db file exists
            db_path = self._url.split(":///", 1)[-1]
            if db_path and db_path != ":memory:":
                Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        try:
            self._engine = create_async_engine(self._url, pool_pre_ping=True)
            async with self._engine.begin() as conn:
                await self._migrate(conn)
            self._ready = True
            logger.info("Database ready (%s, schema v%d)", self._url.split("://")[0], SCHEMA_VERSION)
        except Exception as exc:
            logger.exception("Failed to connect/migrate database")
            raise DatabaseError("Database initialisation failed.", original=exc) from exc

    async def close(self) -> None:
        if self._engine is not None:
            await self._engine.dispose()
            self._engine = None
            self._ready = False
            logger.info("Database connection closed.")

    async def _migrate(self, conn: AsyncConnection) -> None:
        await conn.execute(
            text("CREATE TABLE IF NOT EXISTS bot_schema_version (version INTEGER NOT NULL)")
        )
        current = 0
        rows = (await conn.execute(text("SELECT MAX(version) AS v FROM bot_schema_version"))).mappings().all()
        if rows and rows[0]["v"] is not None:
            current = int(rows[0]["v"])
        for version, migrate in MIGRATIONS:
            if version > current:
                logger.info("Applying migration v%d ...", version)
                await migrate(conn, self._engine.dialect.name if self._engine else "sqlite")
                await conn.execute(
                    text("INSERT INTO bot_schema_version (version) VALUES (:v)"), {"v": version}
                )

    # -- transactions ----------------------------------------------------------

    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[AsyncConnection]:
        """Async context manager: COMMIT on success, ROLLBACK on error."""
        if self._engine is None:
            raise DatabaseError("Database not connected.")
        async with self._engine.connect() as conn:
            async with conn.begin():
                try:
                    yield conn
                except Exception as exc:
                    logger.error("Transaction rolled back: %s", exc, exc_info=exc)
                    raise

    # -- convenience query helpers ----------------------------------------------

    @staticmethod
    def _params(params: Sequence[Any] | Mapping[str, Any]) -> Mapping[str, Any]:
        if isinstance(params, Mapping):
            return params
        return dict(enumerate(params))  # positional binds are not used by this codebase

    @staticmethod
    def _statement(sql: "str | TextClause") -> TextClause:
        return sql if isinstance(sql, TextClause) else text(sql)

    async def execute(self, sql: "str | TextClause", params: Mapping[str, Any] | Sequence[Any] = ()) -> int:
        """Run a single statement in its own transaction; return rowcount."""
        async with self.transaction() as conn:
            result = await conn.execute(self._statement(sql), self._params(params))
            return result.rowcount

    async def insert_returning_id(self, sql: "str | TextClause", params: Mapping[str, Any] | Sequence[Any] = ()) -> int:
        """INSERT with ``RETURNING id`` (supported by both backends)."""
        async with self.transaction() as conn:
            result = await conn.execute(self._statement(sql), self._params(params))
            return int(result.scalar_one())

    async def fetch_one(self, sql: "str | TextClause", params: Mapping[str, Any] | Sequence[Any] = ()) -> Row | None:
        if self._engine is None:
            raise DatabaseError("Database not connected.")
        async with self._engine.connect() as conn:
            result = await conn.execute(self._statement(sql), self._params(params))
            row = result.mappings().first()
            return dict(row) if row is not None else None

    async def fetch_all(self, sql: "str | TextClause", params: Mapping[str, Any] | Sequence[Any] = ()) -> list[Row]:
        if self._engine is None:
            raise DatabaseError("Database not connected.")
        async with self._engine.connect() as conn:
            result = await conn.execute(self._statement(sql), self._params(params))
            return [dict(r) for r in result.mappings().all()]

    async def fetch_val(self, sql: "str | TextClause", params: Mapping[str, Any] | Sequence[Any] = ()) -> Any:
        if self._engine is None:
            raise DatabaseError("Database not connected.")
        async with self._engine.connect() as conn:
            result = await conn.execute(self._statement(sql), self._params(params))
            return result.scalar()
